# Generated by Django 5.2.1 on 2025-05-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_cook_delete_cookie_dish_description_dish_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'ordering': ('-years_of_experience',), 'verbose_name': 'Cook', 'verbose_name_plural': 'Cooks'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
